"""New blog field 'picture_map'; change blog.brief to type Text

Revision ID: 116e8a98400c
Revises: cd315075c977
Create Date: 2023-02-03 13:17:39.235324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116e8a98400c'
down_revision = 'cd315075c977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_map', sa.Text(), nullable=True))
        batch_op.alter_column('brief',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('brief',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('picture_map')

    # ### end Alembic commands ###
