"""Added more logging information

Revision ID: 139248c29166
Revises: 
Create Date: 2022-11-17 23:00:16.028200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139248c29166'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip__logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sec_ch_ua', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip__logs', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('reference')
        batch_op.drop_column('platform')
        batch_op.drop_column('mobile')
        batch_op.drop_column('sec_ch_ua')

    # ### end Alembic commands ###
