"""Initial migration

Revision ID: 2f7ab3931b33
Revises: Creates all the tables for the first time.
Create Date: 2023-02-01 16:46:06.940937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7ab3931b33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'admin',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('email', sa.String(length=40), nullable=False),
        sa.Column('password', sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_table(
        'category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('uuid', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'contact',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('subject', sa.String(), nullable=True),
        sa.Column('message', sa.String(), nullable=True),
        sa.Column('ip', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'ip__logs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('ip', sa.String(), nullable=True),
        sa.Column('sec_ch_ua', sa.String(), nullable=True),
        sa.Column('mobile', sa.String(), nullable=True),
        sa.Column('platform', sa.String(), nullable=True),
        sa.Column('reference', sa.String(), nullable=True),
        sa.Column('user_agent', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'projects',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('html', sa.Text(), nullable=True),
        sa.Column('markdown', sa.Text(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('brief', sa.String(), nullable=True),
        sa.Column('img', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'url__redirection',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('keyword_in', sa.String(), nullable=True),
        sa.Column('url_out', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'blog',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('html', sa.Text(), nullable=True),
        sa.Column('markdown', sa.Text(), nullable=True),
        sa.Column('brief', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    op.drop_table('url__redirection')
    op.drop_table('projects')
    op.drop_table('ip__logs')
    op.drop_table('contact')
    op.drop_table('category')
    op.drop_table('admin')
    # ### end Alembic commands ###
